// Pre-built demo forms to load on startup
export const DEMO_FORMS = [
  {
    id: 'job-application',
    title: 'Job Application',
    description: 'Apply for open positions at our company',
    fields: [
      { id: 'f1', type: 'heading', label: 'Personal Information', level: 'h2', helpText: '', width: 'full', condition: null },
      { id: 'f2', type: 'short_text', label: 'Full Name', placeholder: 'John Doe', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'f3', type: 'email', label: 'Email Address', placeholder: 'john@example.com', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'f4', type: 'phone', label: 'Phone Number', placeholder: '+1 (555) 000-0000', required: false, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'f5', type: 'divider', label: 'Position Details', helpText: '', width: 'full', condition: null },
      { id: 'f6', type: 'dropdown', label: 'Department', placeholder: 'Select a department', required: true, helpText: 'Choose the team you want to join', options: ['Engineering', 'Design', 'Marketing', 'Sales', 'Operations'], validation: {}, condition: null, width: 'full' },
      { id: 'f7', type: 'radio_group', label: 'Employment Type', required: true, helpText: '', options: ['Full-time', 'Part-time', 'Contract', 'Internship'], validation: {}, condition: null, width: 'full' },
      { id: 'f8', type: 'number', label: 'Expected Salary (USD)', placeholder: '75000', required: false, helpText: 'Annual salary expectation', validation: { min: '30000', max: '500000' }, condition: null, width: 'full' },
      { id: 'f9', type: 'divider', label: 'Experience', helpText: '', width: 'full', condition: null },
      { id: 'f10', type: 'slider', label: 'Years of Experience', required: true, helpText: '', validation: { min: '0', max: '20', step: '1' }, condition: null, width: 'full' },
      { id: 'f11', type: 'long_text', label: 'Cover Letter', placeholder: 'Tell us why you\'re a great fit...', required: true, helpText: 'Max 500 words', validation: { maxLength: '2000' }, condition: null, width: 'full' },
      { id: 'f12', type: 'checkbox_group', label: 'Skills', required: false, helpText: 'Select all that apply', options: ['JavaScript', 'Python', 'React', 'Node.js', 'SQL', 'AWS'], validation: {}, condition: null, width: 'full' },
      { id: 'f13', type: 'file', label: 'Resume / CV', required: true, helpText: 'PDF or DOCX, max 5MB', validation: {}, condition: null, width: 'full' },
      { id: 'f14', type: 'checkbox', label: 'I agree to the terms and conditions', placeholder: 'I agree to the terms and conditions', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
    ],
  },
  {
    id: 'customer-feedback',
    title: 'Customer Feedback',
    description: 'Help us improve by sharing your experience',
    fields: [
      { id: 'g1', type: 'heading', label: 'Your Experience', level: 'h2', helpText: '', width: 'full', condition: null },
      { id: 'g2', type: 'rating', label: 'Overall Satisfaction', required: true, helpText: 'How satisfied are you overall?', validation: { max: '5' }, condition: null, width: 'full' },
      { id: 'g3', type: 'radio_group', label: 'How did you hear about us?', required: false, helpText: '', options: ['Google Search', 'Social Media', 'Friend / Referral', 'Advertisement', 'Other'], validation: {}, condition: null, width: 'full' },
      { id: 'g4', type: 'dropdown', label: 'Product / Service Used', placeholder: 'Select one...', required: true, helpText: '', options: ['Starter Plan', 'Pro Plan', 'Enterprise Plan', 'Free Trial'], validation: {}, condition: null, width: 'full' },
      { id: 'g5', type: 'divider', label: 'Detailed Feedback', helpText: '', width: 'full', condition: null },
      { id: 'g6', type: 'checkbox_group', label: 'What did you like?', required: false, helpText: '', options: ['Ease of use', 'Performance', 'Customer support', 'Pricing', 'Features'], validation: {}, condition: null, width: 'full' },
      { id: 'g7', type: 'long_text', label: 'What could we improve?', placeholder: 'Share your thoughts...', required: false, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'g8', type: 'toggle', label: 'Would you recommend us to a friend?', required: false, helpText: '', defaultValue: false, validation: {}, condition: null, width: 'full' },
      { id: 'g9', type: 'short_text', label: 'Your Name (optional)', placeholder: 'Anonymous', required: false, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'g10', type: 'email', label: 'Email for follow-up (optional)', placeholder: 'you@example.com', required: false, helpText: 'We\'ll only contact you if you want a follow-up', validation: {}, condition: { fieldId: 'g8', operator: 'equals', value: 'true' }, width: 'full' },
    ],
  },
  {
    id: 'event-registration',
    title: 'Event Registration',
    description: 'Register for our upcoming annual conference',
    fields: [
      { id: 'h1', type: 'short_text', label: 'First Name', placeholder: 'Jane', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'h2', type: 'short_text', label: 'Last Name', placeholder: 'Smith', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'h3', type: 'email', label: 'Email Address', placeholder: 'jane@company.com', required: true, helpText: 'Confirmation will be sent here', validation: {}, condition: null, width: 'full' },
      { id: 'h4', type: 'short_text', label: 'Company / Organization', placeholder: 'Acme Corp', required: false, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'h5', type: 'divider', label: 'Ticket & Sessions', helpText: '', width: 'full', condition: null },
      { id: 'h6', type: 'radio_group', label: 'Ticket Type', required: true, helpText: '', options: ['General Admission — $99', 'VIP — $299', 'Virtual Attendance — $49'], validation: {}, condition: null, width: 'full' },
      { id: 'h7', type: 'checkbox_group', label: 'Sessions of Interest', required: false, helpText: 'Select all you plan to attend', options: ['Keynote', 'Workshop A: AI & Automation', 'Workshop B: Design Systems', 'Panel: Future of Work', 'Networking Lunch'], validation: {}, condition: null, width: 'full' },
      { id: 'h8', type: 'dropdown', label: 'Dietary Requirements', placeholder: 'Select if applicable', required: false, helpText: '', options: ['None', 'Vegetarian', 'Vegan', 'Gluten-free', 'Halal', 'Kosher'], validation: {}, condition: null, width: 'full' },
      { id: 'h9', type: 'date', label: 'Preferred Check-in Date', required: true, helpText: 'Conference runs Oct 14–16', validation: {}, condition: null, width: 'full' },
      { id: 'h10', type: 'long_text', label: 'Special Requests', placeholder: 'Accessibility needs, questions...', required: false, helpText: '', validation: {}, condition: null, width: 'full' },
      { id: 'h11', type: 'checkbox', label: 'I agree to the event terms and code of conduct', placeholder: 'I agree to the event terms and code of conduct', required: true, helpText: '', validation: {}, condition: null, width: 'full' },
    ],
  },
]
